Repository Solvro/testing-course, pull requests merged in 2025-06, with the labels that each got.

#15 feat: add coverage script from vitest
  1. Unit testing/package-lock.json
  1. Unit testing/package.json
Labels: size/XS

#56 feat: react testing basics
  .github/workflows/react-tests.yml
  .github/workflows/unit-tests.yml
  1. Unit testing/3. Static analysis/README.md
  2a. React/.gitignore
  2a. React/1. Basics/README.md
  2a. React/1. Basics/solvro-projects-combobox.test.ts
  2a. React/README.md
  2a. React/components.json
  2a. React/eslint.config.js
  2a. React/index.html
  2a. React/package-lock.json
  2a. React/package.json
  2a. React/src/App.tsx
  2a. React/src/components/solvro-projects-combobox.tsx
  2a. React/src/components/ui/button.tsx
  2a. React/src/components/ui/command.tsx
  2a. React/src/components/ui/dialog.tsx
  2a. React/src/components/ui/popover.tsx
  2a. React/src/index.css
  2a. React/src/lib/utils.ts
  2a. React/src/main.tsx
  2a. React/src/vite-env.d.ts
  2a. React/tsconfig.app.json
  2a. React/tsconfig.json
  2a. React/tsconfig.node.json
  2a. React/vite.config.ts
Labels: size/XXL

#84 feat: update backend part of course
  2b. Backend/1. API Basics/adonisrc.ts
  2b. Backend/1. API Basics/tests/Task 01 - Course group/course.spec.ts
  2b. Backend/1. API Basics/tests/Task 01 - Registration/registration.test.ts
  2b. Backend/1. API Basics/tests/Task 02 - Exam conflicts/examConflicts.test.ts
  2b. Backend/1. API Basics/tests/Task 02 - Registration/registration.spec.ts
  2b. Backend/1. API Basics/tests/Task 03 - Students/students.spec.ts
  2b. Backend/1. API Basics/tests/Task 03 - Supervisor Manager/supervisorManager.test.ts
  2b. Backend/1. API Basics/tests/bootstrap.ts
  README.md
Labels: size/M

#89 fix: update React course milestones and review stages
  README.md
Labels: size/S

#94 fix: config errors
  2b. Backend/1. API Basics/adonisrc.ts
  2b. Backend/1. API Basics/tests/bootstrap.ts
Labels: size/XS

#118 chore: update timeline
  README.md
Labels: size/S

#119 chore: format files
  2a. React/3. Advanced tests/components.json
  2a. React/3. Advanced tests/eslint.config.js
  2a. React/3. Advanced tests/index.html
  2a. React/3. Advanced tests/src/api/api-z-planer-mock-api-dla-ciekawskich.ts
  2a. React/3. Advanced tests/src/components/providers.tsx
  2a. React/3. Advanced tests/src/components/ui/button.tsx
  2a. React/3. Advanced tests/src/components/ui/command.tsx
  2a. React/3. Advanced tests/src/components/ui/dialog.tsx
  2a. React/3. Advanced tests/src/components/ui/form.tsx
  2a. React/3. Advanced tests/src/components/ui/input-otp.tsx
  2a. React/3. Advanced tests/src/components/ui/input.tsx
  2a. React/3. Advanced tests/src/components/ui/label.tsx
  2a. React/3. Advanced tests/src/components/ui/popover.tsx
  2a. React/3. Advanced tests/src/contexts/auth-context-definition.ts
  2a. React/3. Advanced tests/src/contexts/auth-context.tsx
  2a. React/3. Advanced tests/src/lib/utils.ts
  2a. React/3. Advanced tests/src/main.tsx
  2a. React/3. Advanced tests/src/pages/plans.tsx
Labels: size/L
